/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{curationId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증된 사용자가 큐레이션에 좋아요
         * @description 인증된 사용자가 큐레이션에 좋아요를 합니다.
         */
        post: operations["likeSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 자체 회원가입
         */
        post: operations["userSignUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 자체 로그인
         */
        post: operations["userSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location/{curationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증된 사용자가 위치 생성
         * @description 인증된 사용자가 위치를 생성(큐레이션 id, 위치 이름, 이미지)합니다.
         */
        post: operations["locationSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 사용자가 큐레이션 6개씩 조회
         * @description 모든 사용자가 산책로 지도 페이지에서 큐레이션을 한 페이지 당 6개씩 조회합니다.
         */
        get: operations["curationFindAll"];
        put?: never;
        /**
         * 인증된 사용자가 큐레이션 생성
         * @description 인증된 사용자가 산책로 생성 페이지에서 큐레이션을 생성합니다.
         */
        post: operations["curationSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commentSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 사용자 정보 수정
         * @description 사용자의 정보(이름, 이메일, 비밀번호)를 수정합니다.
         */
        patch: operations["userInfoUpdate"];
        trace?: never;
    };
    "/location/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 인증된 사용자가 위치 삭제
         * @description 인증된 사용자가 위치를 삭제합니다.
         */
        delete: operations["locationDelete"];
        options?: never;
        head?: never;
        /**
         * 인증된 사용자가 위치 수정
         * @description 인증된 사용자가 위치를 수정(위치 이름, 이미지(선택), 주소)합니다.
         */
        patch: operations["locationUpdate"];
        trace?: never;
    };
    "/curation/{curationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 사용자가 큐레이션 하나씩 조회
         * @description 모든 사용자가 산책로 지도 페이지에서 큐레이션 한 개씩 조회합니다.
         */
        get: operations["curationFindOne"];
        put?: never;
        post?: never;
        /**
         * 인증된 사용자가 큐레이션 삭제
         * @description 인증된 사용자가 큐레이션을 삭제합니다.
         */
        delete: operations["curationDelete"];
        options?: never;
        head?: never;
        /**
         * 인증된 사용자가 큐레이션 수정
         * @description 인증된 사용자가 산책로 지도 페이지에서 큐레이션을 수정(큐레이션 제목, 설명)합니다.
         */
        patch: operations["curationUpdate"];
        trace?: never;
    };
    "/comment/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["commentDelete"];
        options?: never;
        head?: never;
        patch: operations["commentUpdate"];
        trace?: never;
    };
    "/user/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 사용자가 큐레이션을 가장 많이 작성한 6명의 큐레이터 조회
         * @description 모든 사용자는 랜딩 페이지에서 큐레이션을 가장 많이 작성한 6명의 큐레이터를 볼 수 있습니다.
         */
        get: operations["findByOrderByCurationsCurationCountDesc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login/oauth2/code/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 구글 로그인
         * @description 구글 로그인
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 인증된 사용자가 고른 위치 조회
         * @description 인증된 사용자가 고른 위치를 조회합니다.
         */
        get: operations["locationFindAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curation/user/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 인증된 사용자가 자신이 좋아요 누른 큐레이션 조회
         * @description 인증된 사용자가 마이페이지에서 자신이 좋아요 누른 큐레이션 목록을 6개씩 조회합니다.
         */
        get: operations["findCurationUserLikes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curation/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 사용자가 큐레이션 검색
         * @description 모든 사용자가 산책로 지도 페이지에서 큐레이션을 검색합니다.
         */
        get: operations["searchCurations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curation/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 사용자가 최신순으로 정렬된 큐레이션 6개 조회
         * @description 모든 사용자가 랜딩페이지에서 최신순으로 정렬된 6개의 큐레이션을 조회합니다.
         */
        get: operations["findTop6ByOrderByCreateDateDesc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curation/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 사용자가 좋아요 순으로 정렬된 큐레이션 6개 조회
         * @description 모든 사용자가 랜딩페이지에서 좋아요 순으로 정렬된 6개의 큐레이션을 조회합니다.
         */
        get: operations["findTop6ByOrderByLikeCountDesc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{curationId}/unlike": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 인증된 사용자가 큐레이션에 좋아요 취소
         * @description 인증된 사용자가 큐레이션에 좋아요를 취소합니다.
         */
        delete: operations["likeDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseTemplateString: {
            status?: string;
            message?: string;
            data?: string;
        };
        ApiResponseTemplateSuccessCode: {
            status?: string;
            message?: string;
            /** @enum {string} */
            data?: "GET_SUCCESS" | "LOCATION_UPDATE_SUCCESS" | "CURATION_UPDATE_SUCCESS" | "COMMENT_UPDATE_SUCCESS" | "LOCATION_DELETE_SUCCESS" | "CURATION_DELETE_SUCCESS" | "COMMENT_DELETE_SUCCESS" | "LIKE_DELETE_SUCCESS" | "USER_SIGNUP_SUCCESS" | "USER_LOGIN_SUCCESS" | "USER_INFO_UPDATE_SUCCESS" | "LOCATION_SAVE_SUCCESS" | "CURATION_SAVE_SUCCESS" | "COMMENT_SAVE_SUCCESS" | "LIKE_SAVE_SUCCESS";
        };
        UserSignUpReqDto: {
            name: string;
            email: string;
            password: string;
            accessToken?: string;
            refreshToken?: string;
            /** @enum {string} */
            role?: "ROLE_USER";
        };
        UserSignInReqDto: {
            email: string;
            password: string;
            accessToken?: string;
            refreshToken?: string;
        };
        ApiResponseTemplateUserSignInResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["UserSignInResDto"];
        };
        UserSignInResDto: {
            name?: string;
            email?: string;
            accessToken?: string;
            refreshToken?: string;
        };
        LocationSaveReqDto: {
            name?: string;
            description?: string;
            address?: string;
        };
        ApiResponseTemplateLocationInfoResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["LocationInfoResDto"];
        };
        LocationInfoResDto: {
            /** Format: int64 */
            locationId?: number;
            /** Format: int64 */
            curationId?: number;
            name?: string;
            description?: string;
            address?: string;
            locationImage?: string;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            latitude?: number;
        };
        CurationSaveReqDto: {
            name?: string;
            content?: string;
        };
        ApiResponseTemplateCurationInfoResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["CurationInfoResDto"];
        };
        CurationInfoResDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            content?: string;
            /** Format: date-time */
            createDate?: string;
            /** Format: int32 */
            likeCount?: number;
            locations?: components["schemas"]["LocationInfoResDto"][];
        };
        CommentSaveReqDto: {
            /** Format: int64 */
            id?: number;
            name: string;
            comment: string;
            curation?: components["schemas"]["Curation"];
        };
        Curation: {
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifiedDate?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
            content?: string;
            /** Format: int32 */
            likeCount?: number;
            locations?: components["schemas"]["Location"][];
            user?: components["schemas"]["User"];
            likes?: components["schemas"]["Like"][];
        };
        Like: {
            /** Format: int64 */
            id?: number;
            user?: components["schemas"]["User"];
        };
        Location: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            latitude?: number;
            curation?: components["schemas"]["Curation"];
            user?: components["schemas"]["User"];
        };
        User: {
            /** Format: int64 */
            id?: number;
            name?: string;
            email?: string;
            password?: string;
            accessToken?: string;
            refreshToken?: string;
            /** @enum {string} */
            role?: "ROLE_USER";
            curations?: components["schemas"]["Curation"][];
            locations?: components["schemas"]["Location"][];
            likes?: components["schemas"]["Like"][];
            /** Format: int32 */
            curationCount?: number;
        };
        ApiResponseTemplate: {
            status?: string;
            message?: string;
            data?: Record<string, never>;
        };
        UserInfoUpdateReqDto: {
            name: string;
            password: string;
            email: string;
        };
        ApiResponseTemplateUserInfoResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["UserInfoResDto"];
        };
        UserInfoResDto: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            email?: string;
        };
        LocationUpdateReqDto: {
            name?: string;
            description?: string;
            address?: string;
        };
        CurationUpdateReqDto: {
            name?: string;
            content?: string;
        };
        CommentUpdateReqDto: {
            comment: string;
        };
        ApiResponseTemplateUserPopularListResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["UserPopularListResDto"];
        };
        UserPopularInfoResDto: {
            name?: string;
            /** Format: int32 */
            curationCount?: number;
        };
        UserPopularListResDto: {
            userPopular?: components["schemas"]["UserPopularInfoResDto"][];
        };
        GoogleToken: {
            accessToken?: string;
        };
        ApiResponseTemplateLocationListResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["LocationListResDto"];
        };
        LocationListResDto: {
            locations?: components["schemas"]["LocationInfoResDto"][];
        };
        ApiResponseTemplateCurationListResDto: {
            status?: string;
            message?: string;
            data?: components["schemas"]["CurationListResDto"];
        };
        CurationListResDto: {
            curations?: components["schemas"]["CurationInfoResDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    likeSave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateSuccessCode"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateSuccessCode"];
                };
            };
        };
    };
    userSignUp: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSignUpReqDto"];
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
        };
    };
    userSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSignInReqDto"];
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateUserSignInResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateUserSignInResDto"];
                };
            };
        };
    };
    locationSave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curationId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    location: components["schemas"]["LocationSaveReqDto"];
                    /** Format: binary */
                    locationImage?: string;
                };
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateLocationInfoResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateLocationInfoResDto"];
                };
            };
        };
    };
    curationFindAll: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 서버 내부 오류입니다. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
        };
    };
    curationSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurationSaveReqDto"];
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
        };
    };
    commentSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentSaveReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
        };
    };
    userInfoUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInfoUpdateReqDto"];
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateUserInfoResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateUserInfoResDto"];
                };
            };
        };
    };
    locationDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
        };
    };
    locationUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    location: components["schemas"]["LocationUpdateReqDto"];
                    /** Format: binary */
                    locationImage?: string;
                };
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateLocationInfoResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateLocationInfoResDto"];
                };
            };
        };
    };
    curationFindOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 서버 내부 오류입니다. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
        };
    };
    curationDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateSuccessCode"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateSuccessCode"];
                };
            };
        };
    };
    curationUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curationId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurationUpdateReqDto"];
            };
        };
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationInfoResDto"];
                };
            };
        };
    };
    commentDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
        };
    };
    commentUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
        };
    };
    findByOrderByCurationsCurationCountDesc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateUserPopularListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateUserPopularListResDto"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleToken"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleToken"];
                };
            };
        };
    };
    locationFindAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateLocationListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateLocationListResDto"];
                };
            };
        };
    };
    findCurationUserLikes: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 서버 내부 오류입니다. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
        };
    };
    searchCurations: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 서버 내부 오류입니다. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
        };
    };
    findTop6ByOrderByCreateDateDesc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 서버 내부 오류입니다. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
        };
    };
    findTop6ByOrderByLikeCountDesc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 서버 내부 오류입니다. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateCurationListResDto"];
                };
            };
        };
    };
    likeDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 생성에 성공하였습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateSuccessCode"];
                };
            };
            /** @description 잘못된 요청입니다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateString"];
                };
            };
            /** @description 인증이 필요합니다. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTemplateSuccessCode"];
                };
            };
        };
    };
}
